services:
  db:
    image: postgres:16-alpine
    container_name: student_db
    environment:
      POSTGRES_DB: student_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: student_app
    environment:
      PORT: 8080
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_x0wBbEUFCsI6
      DATABASE_URL: jdbc:postgresql://ep-delicate-frog-a1bjrklo-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    ports:
      - "8080:8080"

volumes:
  pgdata: