services:
  db:
    image: postgres:16-alpine
    container_name: student_db
    environment:
      POSTGRES_DB: student_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: student_app
    depends_on:
      - db
    environment:
      PORT: 8080
      DATABASE_URL: jdbc:postgresql://db:5432/student_management
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    ports:
      - "8080:8080"

volumes:
  pgdata: